name       : python-feedparser
version    : 6.0.11
release    : 12
source     :
    - https://pypi.python.org/packages/source/f/feedparser/feedparser-6.0.11.tar.gz : c9d0407b64c6f2a065d0ebb292c2b35c01050cc0dc33757461aaabdc4c4184d5
homepage   : https://pypi.org/project/feedparser/
license    :
    - BSD-2-Clause
    - MIT
component  : programming.python
summary    : Universal feed parser
description: |
    Universal feed parser, handles RSS 0.9x, RSS 1.0, RSS 2.0, CDF, Atom 0.3, and Atom 1.0 feeds.
build      : |
    %python3_setup
install    : |
    %python3_install
