name       : gapless
version    : '3.8'
release    : 8
source     :
    - https://gitlab.gnome.org/neithern/g4music/-/archive/v3.8/g4music-v3.8.tar.bz2 : 72cf4eec9a249416807334f28e49943d3ae184fe6793c171fe783bbe776fc86c
homepage   : https://gitlab.gnome.org/neithern/g4music
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Play your music elegantly
description: |
    Gapless (AKA: G4Music) is a lightweight music player written in GTK4, with a beautiful and adaptive user interface, focuses on high performance for large music collection.
builddeps  :
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - g4music
    - dbginfo : g4music-dbginfo
