name       : melonds
version    : 0.9.5
release    : 1
source     :
    - https://github.com/melonDS-emu/melonDS/archive/refs/tags/0.9.5.tar.gz : 52c6b99340b8bba8c52b11a2242591f05e838c34ddd9ec20dcf1a6039405434a
homepage   : https://melonds.kuribo64.net/
license    : GPL-3.0-or-later
component  : games.emulator
summary    : DS emulator, sorta
description: |
    melonDS aims at providing fast and accurate Nintendo DS emulation.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(libarchive)
    - pkgconfig(libpcap)
    - pkgconfig(libzstd)
    - pkgconfig(slirp)
    - pkgconfig(sdl2)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    sed -i '/Icon/a StartupWMClass=melonDS' res/net.kuribo64.melonDS.desktop
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/net.kuribo64.melonDS.appdata.xml -t $installdir/usr/share/metainfo/
